/*
 * encurtador API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateUrl {
    #[serde(rename = "url")]
    pub url: String,
}

impl CreateUrl {
    pub fn new(url: String) -> CreateUrl {
        CreateUrl {
            url,
        }
    }
}


