/*
 * encurtador API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UrlResponse {
    #[serde(rename = "shortened")]
    pub shortened: String,
}

impl UrlResponse {
    pub fn new(shortened: String) -> UrlResponse {
        UrlResponse {
            shortened,
        }
    }
}


